version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:6000"
    volumes:
      - .:/app  # Mount the project code
      - ./static:/app/static  # Persist static files
      - ./media:/app/media  # Persist media files if needed
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ORACLE_DB_USER=prkardata
      - ORACLE_DB_PASSWORD=s5j7d~qD}PU?Hx{N$Wb+:E
      - ORACLE_DB_HOST=10.2.10.20
      - ORACLE_DB_NAME=dbdev
      - ORACLE_DB_PORT=1521
  #   depends_on:
  #     - db

  # db:
  #   image: container-registry.oracle.com/database/express:21.3.0
  #   environment:
  #     - ORACLE_PASSWORD=your_oracle_password
  #   volumes:
  #     - db_data:/opt/oracle/oradata  # Persist Oracle database data
  
# volumes:
#   static_volume:
#   media_volume:  # Optional, for media files if needed
#   db_data: