# Generated by Django 5.0.2 on 2024-08-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityDuringAccident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "activity_during_accident",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InsAccidentAgentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("createdat", models.DateTimeField()),
                ("createdby", models.BigIntegerField()),
                ("modifiedat", models.DateTimeField(blank=True, null=True)),
                ("modifiedby", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "ins_accident_agent_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InsActivityDuringAccident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=255)),
                ("createdat", models.DateTimeField()),
                ("createdby", models.BigIntegerField()),
                ("modifiedat", models.DateTimeField(blank=True, null=True)),
                ("modifiedby", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "ins_activity_during_accident",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InsPlaceAccidentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=255)),
                ("createdat", models.DateTimeField()),
                ("createdby", models.BigIntegerField()),
                ("modifiedat", models.DateTimeField(blank=True, null=True)),
                ("modifiedby", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "ins_place_accident_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InsWorkshopActivityFriday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("createdat", models.DateTimeField()),
                ("createdby", models.BigIntegerField()),
                ("modifiedat", models.DateTimeField(blank=True, null=True)),
                ("modifiedby", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "ins_workshop_activity_friday",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="ActivityDuringAccidsent",
        ),
        migrations.DeleteModel(
            name="InsAccidsentAgentType",
        ),
        migrations.DeleteModel(
            name="InsActivityDuringAccidsent",
        ),
        migrations.DeleteModel(
            name="InsPlaceAccidsentType",
        ),
        migrations.DeleteModel(
            name="InsWorkshopActivityFridsay",
        ),
    ]
