# Generated by Django 5.0.2 on 2024-08-14 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0002_activityduringaccident_insaccidentagenttype_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Unemploymentreason",
        ),
    ]
