# Generated by Django 5.0.2 on 2024-08-14 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0005_zone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Zone",
        ),
    ]
