# Generated by Django 5.0.2 on 2024-08-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0010_delete_zone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("province_id", models.CharField(max_length=40)),
                (
                    "province_enum",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "province_name",
                    models.CharField(blank=True, max_length=4000, null=True),
                ),
                ("city_id", models.CharField(max_length=40)),
                ("city_enum", models.CharField(blank=True, max_length=40, null=True)),
                ("city_name", models.CharField(blank=True, max_length=4000, null=True)),
                ("municipality_id", models.CharField(max_length=40)),
                (
                    "municipality_enum",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "municipality_name",
                    models.CharField(blank=True, max_length=4000, null=True),
                ),
            ],
            options={
                "db_table": "zone_",
                "managed": False,
            },
        ),
    ]
