# Generated by Django 5.0.2 on 2024-08-14 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0011_zone"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="location",
            table="LOCATION",
        ),
    ]
