# Generated by Django 5.0.2 on 2024-08-21 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0014_alter_officestaff_options_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "پروفایل", "verbose_name_plural": "پروفایل"},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={
                "managed": False,
                "verbose_name": "نقش",
                "verbose_name_plural": "نقش ها",
            },
        ),
    ]
