# Generated by Django 5.0.2 on 2024-08-21 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0015_alter_profile_options_alter_role_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="foreignerids",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="ids",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="idsno",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_converted",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="ispermittedtoreceivebyemail",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="ispermittedtoreceivebyfax",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="militaryservicestatus",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="nationalids",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="parentlocation",
        ),
        migrations.AddField(
            model_name="profile",
            name="NATIONALID",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="کدملی"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="activefrom",
            field=models.DateTimeField(blank=True, null=True, verbose_name="فعال از"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="activeto",
            field=models.DateTimeField(blank=True, null=True, verbose_name="فعال تا"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="آدرس"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birth_place",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="محل تحولد"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birthdate",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ تولد"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="childrennumber",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="تعداد فرزند"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="createdat",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="createdby",
            field=models.BigIntegerField(
                blank=True, default=1, null=True, verbose_name="ایجاد شده توسط"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="currenttaminworkshopcode",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="deathdate",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ فوت"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="defunctdate",
            field=models.BigIntegerField(blank=True, null=True, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="آدرس پستی"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="externalusertype",
            field=models.IntegerField(blank=True, null=True, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="fathername",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="نام پدر"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="faxnumber",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="نمابر"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="firstname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="نام"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="force_password_change",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="وضعیت تعویض کلمه عبور"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="force_profile_completion",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="وضعیت تکمیل پروفایل"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="foundationdate",
            field=models.BigIntegerField(blank=True, null=True, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="جنسیت"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="graduation",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="سطح تحصیلات"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="graduationlevel",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="سطح تحصیل"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="isactive",
            field=models.BigIntegerField(
                blank=True, default=1, null=True, verbose_name="وضعیت کاربر"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="lastname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="نام خانوادگی"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="شهر"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="maritalstatus",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="وضعیت تاهل"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mobilenumber",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="تلفن همراه"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="modifiedat",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="modifiedby",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="بروزرسانی شده"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nationalcertificatecode",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nationalcertificateserial",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="officialemail",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="organizationname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="سازمان"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="password",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="کلمه عبور"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phonenumber",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="شماره ثابت"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="physicalcondition",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="وضعیت جسمانی"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="postalcode",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="کدپستی"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="religion",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="مذهب"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="secretkey",
            field=models.CharField(
                blank=True, max_length=4000, null=True, verbose_name="کلید رمز"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="نام کاربری",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="usertype",
            field=models.ForeignKey(
                blank=True,
                db_column="usertype",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="backoffice.roletype",
                verbose_name="نوع کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="zonecode",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="منطقه"
            ),
        ),
    ]
