# Generated by Django 5.0.2 on 2024-10-30 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0017_customthem_alter_commeeting_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backoffice.location",
            ),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="DJANGO_USER",
        ),
    ]
