# Generated by Django 5.0.2 on 2024-10-30 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "backoffice",
            "0018_alter_customuser_options_alter_customuser_province_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="province",
            field=models.ForeignKey(
                blank=True,
                db_column="province",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="backoffice.location",
            ),
        ),
    ]
