# Generated by Django 5.0.2 on 2024-10-30 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0021_alter_customuser_province"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backoffice.location",
            ),
        ),
    ]
